using System.ServiceModel;
using BuildFetcher;
using BuildFetcher.AutoGeneratedClasses;

namespace Build_Service
{
    [ServiceContract]
    public interface IBuildService
    {
        [OperationContract]
        Build GetCurrentBuild(string jobName);
        
        [OperationContract]
        Build GetBuild(string jobName, int buildnumber);
    }

    public class BuildService : IBuildService
    {
        IHudsonBuildFetcher buildFetcher;
        IHudsonJobFetcher jobFetcher;
		
        public BuildService(IHudsonBuildFetcher buildFetcher, IHudsonJobFetcher jobFetcher)
        {
            this.buildFetcher = buildFetcher;
            this.jobFetcher = jobFetcher;
        }

        public Build GetCurrentBuild(string jobName)
        {
            var job = jobFetcher.GetJobFromJobName(jobName);

            return GetBuild(jobName, job.LastBuild.number);
        }

        public Build GetBuild(string jobName, int buildnumber)
        {
            return buildFetcher.GetBuildFor(jobName, buildnumber);
        }
    }
}