using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Build_Fetcher.AutoGeneratedClasses;

namespace Build_Fetcher.Tests
{
    [TestClass]
    public class WhenRetrievingLastBuildForLiveJob
    {
        static Build build;
        static Job job;
        const string JobName = "ruby";

        [ClassInitialize]
        public static void setup(TestContext ctx)
        {
            var xmlFetcher = new HudsonXmlFetcher();
            var jobFetcher = new HudsonJobFetcher(xmlFetcher);
            var buildFetcher = new HudsonBuildFetcher(xmlFetcher);

            job = jobFetcher.GetJobFromJobName(JobName);

            build = job.GetLastBuildFrom(buildFetcher);
        }

        [TestMethod]
        public void ShouldHaveBuildNumberMatchingBuildsLastBuildNumber()
        {
            Assert.AreEqual(build.number, job.LastCompletedBuild.number);
        }

        [TestMethod]
        public void ShouldHaveResultOfSuccessFailureOrEmpty()
        {
            Assert.IsTrue(build.result == "SUCCESS" || build.result == "FAILURE" || build.result == string.Empty);
        }

        [TestMethod]
        public void ShouldHaveAtLEastOneCulpritName()
        {
            Assert.IsNotNull(build.culprit[0].fullName);
        }
    }
}
