using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using BuildFetcher.AutoGeneratedClasses;
using BuildFetcher;
using System.Configuration;

using System.Xml.Linq;

namespace BuildFetcher_Tests
{
    [TestFixture]
    public class WhenRetrievingLiveJobFromJobName
    {
        Job job;
        const string JobName = "ruby";

        [TestFixtureSetUp]
        public void setup()
        {
			var rootUri = ConfigurationManager.AppSettings["HudsonRootUri"];
			
            var xmlFetcher = new HudsonJobXmlFetcher();
            var jobFetcher = new HudsonJobFetcher(xmlFetcher);

            job = jobFetcher.GetJobFromJobName(JobName);
        }

        [Test]
        public void ShouldHaveRequestedJobName()
        {
            Assert.AreEqual(JobName, job.Name);
        }

        [Test]
        public void ShouldHaveABuildNumber()
        {
            Assert.IsTrue(job.NextBuildNumber > 0);
        }

        [Test]
        public void ShouldHaveALastCompletedBuild()
        {
            Assert.IsTrue(job.LastCompletedBuild.number > 0);
            Assert.IsFalse(string.IsNullOrEmpty(job.LastCompletedBuild.url));
        }

        [Test]
        public void ShouldHaveALastBuild()
        {
            Assert.IsTrue(job.LastBuild.number > 0);
            Assert.IsFalse(string.IsNullOrEmpty(job.LastBuild.url));
        }
    }
}
