using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System.Xml.Serialization;

namespace BuildFetcher.AutoGeneratedClasses
{
    public interface IHudsonJobFetcher
    {
        Job GetJobFromJobName(string jobName);
    }

    public class HudsonJobFetcher : XmlDeserialzer<Job>, IHudsonJobFetcher
    {
        IHudsonJobXmlFetcher hudsonXmlFetcher;

        public HudsonJobFetcher(IHudsonJobXmlFetcher hudsonXmlFetcher) 
        {
            this.hudsonXmlFetcher = hudsonXmlFetcher;
        }

        public Job GetJobFromJobName(string jobName)
        {
            var jobXml = hudsonXmlFetcher.GetJobXmlFor(jobName);

            var job = DeserializeXml(jobXml);

            return job;
        }
    }
}
