using BuildFetcher.AutoGeneratedClasses;

namespace BuildFetcher
{
    public interface IHudsonJobFetcher
    {
        Job GetJobFromJobName(string jobName);
    }

    public class HudsonJobFetcher : XmlDeserialzer<Job>, IHudsonJobFetcher
    {
        IHudsonJobXmlFetcher hudsonXmlFetcher;

        public HudsonJobFetcher(IHudsonJobXmlFetcher hudsonXmlFetcher) 
        {
            this.hudsonXmlFetcher = hudsonXmlFetcher;
        }

        public Job GetJobFromJobName(string jobName)
        {
            var jobXml = hudsonXmlFetcher.GetJobXmlFor(jobName);

            var job = DeserializeXml(jobXml);

            return job;
        }
    }
}
