using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;
using System.Xml.Schema;

namespace BuildFetcher.AutoGeneratedClasses
{
    [Serializable]
    [XmlRoot("freeStyleProject", IsNullable = false)]
    public partial class Job
    {
        [XmlElement("name", Form = XmlSchemaForm.Unqualified)]
        public string Name { get; set; }

        [XmlElement("building", Form = XmlSchemaForm.Unqualified)]
        public bool Building { get; set; }

        [XmlElement("nextBuildNumber", Form = XmlSchemaForm.Unqualified)]
        public int NextBuildNumber { get; set; }

        [XmlElement("lastBuild", Form = XmlSchemaForm.Unqualified)]
        public JobBuild LastBuild { get; set; }

        [XmlElement("lastCompletedBuild", Form = XmlSchemaForm.Unqualified)]
        public JobBuild LastCompletedBuild { get; set; }

        public Build GetLastBuildFrom(HudsonBuildFetcher buildFetcher)
        {
            return buildFetcher.GetBuildFor(Name, LastCompletedBuild.number);
        }
    }

    [Serializable]
    public class JobBuild
    {
        [XmlElement("number", Form = XmlSchemaForm.Unqualified)]
        public int number { get; set; }

        [XmlElement("url", Form = XmlSchemaForm.Unqualified)]
        public string url { get; set; }
    }
}
